### ISSUE TITLE
Crash on orientation changes when using Mortar library

### ISSUE THREAD

**Issue by mkodekar** [michael-rapp/ChromeLikeTabSwitcher#4]
```
FATAL EXCEPTION: main
                                                                    Process: com.origgon.origin, PID: 15723
                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.origgon.origin/com.origgon.origin.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void de.mrapp.android.tabswitcher.layout.ChildRecyclerAdapter.restoreInstanceState(android.os.Bundle)' on a null object reference
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2699)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
                                                                        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4571)
                                                                        at android.app.ActivityThread.-wrap19(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1513)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6236)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
                                                                     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void de.mrapp.android.tabswitcher.layout.ChildRecyclerAdapter.restoreInstanceState(android.os.Bundle)' on a null object reference
                                                                        at de.mrapp.android.tabswitcher.model.TabSwitcherModel.restoreInstanceState(TabSwitcherModel.java:1272)
                                                                        at de.mrapp.android.tabswitcher.TabSwitcher.onRestoreInstanceState(TabSwitcher.java:1441)
                                                                        at android.view.View.dispatchRestoreInstanceState(View.java:15755)
                                                                        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3231)
                                                                        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
                                                                        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
                                                                        at android.view.View.restoreHierarchyState(View.java:15733)
                                                                        at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2108)
                                                                        at android.app.Activity.onRestoreInstanceState(Activity.java:1048)
                                                                        at android.app.Activity.performRestoreInstanceState(Activity.java:1003)
                                                                        at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1175)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2672)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766) 
                                                                        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4571) 
                                                                        at android.app.ActivityThread.-wrap19(ActivityThread.java) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1513) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6236) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781) 
```

my app is working on mortar flow architecture or you may say mvp  , please have a look i will also post the code for the presenter and decorator

```java
package com.origgon.origin.viewpresenter;

import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.design.widget.Snackbar;
import android.support.v4.content.ContextCompat;
import android.support.v4.view.OnApplyWindowInsetsListener;
import android.support.v4.view.ViewCompat;
import android.view.Menu;
import android.view.View;
import android.view.ViewTreeObserver;

import com.origgon.origin.MainActivity;
import com.origgon.origin.R;
import com.origgon.origin.annotation.DaggerScope;
import com.origgon.origin.annotation.Layout;
import com.origgon.origin.appfactory.ComponentFactory;
import com.origgon.origin.applications.Appdependencies;
import com.origgon.origin.util.L;
import com.origgon.origin.util.Utils;
import com.origgon.origin.views.MainViewTabSwicther;
import com.origgon.origin.widgets.Decorator;

import dagger.Provides;
import de.mrapp.android.tabswitcher.Animation;
import de.mrapp.android.tabswitcher.Tab;
import de.mrapp.android.tabswitcher.TabSwitcher;
import de.mrapp.android.tabswitcher.TabSwitcherListener;
import de.mrapp.android.util.ViewUtil;
import flow.path.Path;
import mortar.ViewPresenter;

/**
 * Created by rkodekar on 5/8/17.
 */

@Layout(R.layout.browser_view)
public class MainScreen extends Path implements ComponentFactory<MainActivity.Component> {

    @Override
    public Object createComponent(MainActivity.Component parent) {
        return DaggerMainScreen_Component.builder()
                .component(parent)
                .module(new Module())
                .build();
    }

    @dagger.Component(dependencies = MainActivity.Component.class, modules = Module.class)
    @DaggerScope(Component.class)
    public interface Component extends Appdependencies {
        void inject(MainViewTabSwicther mainViewTabSwicther);
    }

    @dagger.Module
    public class Module {

        @Provides
        @DaggerScope(Component.class)
        public Presenter providePresenter() {
            return new Presenter();
        }
    }

    public static class Presenter extends ViewPresenter<MainViewTabSwicther> implements TabSwitcherListener {

        private int tabCount;
        private Decorator decorator;
        private Snackbar snackbar;
        private TabSwitcher tabSwitcher;

        public interface ViewProvider {
            TabSwitcher tabSwitcher();
        }


        @Override
        public void dropView(MainViewTabSwicther view) {
            super.dropView(view);
        }

        @Override
        protected void onLoad(Bundle savedInstanceState) {
            //super.onLoad(savedInstanceState);
            if (savedInstanceState != null) {
                tabCount = savedInstanceState.getInt(Utils.NUMBEROFTAB);
                L.d("Tab count is  " + String.valueOf(tabCount));
            } else {
                tabCount =1;
                L.d("tab count is " + String.valueOf(tabCount));
                L.d("Tab count is  " + String.valueOf(tabCount));
            }
            tabSwitcher = getView().tabSwitcher();
            decorator = new Decorator(tabSwitcher);
            ViewCompat.setOnApplyWindowInsetsListener(tabSwitcher, createWindowInsetsListener());
            tabSwitcher.setDecorator(decorator);
            tabSwitcher.addListener(this);
            tabSwitcher.showToolbars(true);
            tabSwitcher.setToolbarNavigationIcon(R.drawable.ic_home_black_24dp, createAddTabListener());
            tabSwitcher.inflateToolbarMenu(R.menu.tab_swicther, decorator.createToolbarMenulistener());
            tabSwitcher.getViewTreeObserver().addOnGlobalLayoutListener(createTabSwitcherLayoutListener());
            for (int i = 0; i < tabCount; i++) {
                tabSwitcher.addTab(decorator.createTab(i));
            }
        }

        @Override
        protected void onSave(Bundle outState) {
            super.onSave(outState);
            L.d("onSave is called and tab count is" + String.valueOf(tabCount));
            outState.putInt(Utils.NUMBEROFTAB, tabCount);
        }

        @Override
        public void onSwitcherShown(@NonNull TabSwitcher tabSwitcher) {

        }

        @Override
        public void onSwitcherHidden(@NonNull TabSwitcher tabSwitcher) {
            if (snackbar != null) {
                snackbar.dismiss();
            }
        }

        @Override
        public void onSelectionChanged(@NonNull TabSwitcher tabSwitcher, int selectedTabIndex, @Nullable Tab selectedTab) {

        }

        @Override
        public void onTabAdded(@NonNull TabSwitcher tabSwitcher, int index, @NonNull Tab tab, @NonNull Animation animation) {
            tabCount = tabSwitcher.getCount();
            L.d("tab count is " + String.valueOf(tabCount));
        }

        @Override
        public void onTabRemoved(@NonNull TabSwitcher tabSwitcher, int index, @NonNull Tab tab, @NonNull Animation animation) {
            CharSequence text = getView().getContext().getString(R.string.removed_tab_snackbar, tab.getTitle());
            showUndoSnackBar(text, index, tab);
            tabCount = tabSwitcher.getCount();
            L.d("tab count is " + String.valueOf(tabCount));
        }

        @Override
        public void onAllTabsRemoved(@NonNull TabSwitcher tabSwitcher, @NonNull Tab[] tabs, @NonNull Animation animation) {
            CharSequence text = getView().getContext().getString(R.string.cleared_tabs_snackbar);
            showUndoSnackBar(text, 0, tabs);
            tabCount = 0;
            L.d("tab count is " + String.valueOf(tabCount));
        }

        @NonNull
        private OnApplyWindowInsetsListener createWindowInsetsListener() {
            return (v, insets) -> {
                tabSwitcher.setPadding(insets.getSystemWindowInsetLeft(),
                        insets.getSystemWindowInsetTop(), insets.getSystemWindowInsetRight(),
                        insets.getSystemWindowInsetBottom());
                return insets;
            };
        }

        @NonNull
        private View.OnClickListener createAddTabListener() {
            return v -> {
                int index = tabSwitcher.getCount();
                Animation animation = decorator.createRevealAnimation();
                tabSwitcher.addTab(decorator.createTab(index), 0, animation);
            };
        }

        @NonNull
        private ViewTreeObserver.OnGlobalLayoutListener createTabSwitcherLayoutListener() {
            return new ViewTreeObserver.OnGlobalLayoutListener() {
                @Override
                public void onGlobalLayout() {
                    ViewUtil.removeOnGlobalLayoutListener(tabSwitcher.getViewTreeObserver(), this);
                    Menu menu = tabSwitcher.getToolbarMenu();
                    if (menu != null) {
                        TabSwitcher.setupWithMenu(tabSwitcher, menu, decorator.createTabSwitcherButtonListener());
                    }
                }
            };
        }


        private void showUndoSnackBar(@NonNull final CharSequence text, final int index,
                                      @NonNull Tab... tabs) {
            snackbar = Snackbar.make(tabSwitcher, text, Snackbar.LENGTH_LONG)
                    .setActionTextColor(ContextCompat.getColor(getView().getContext(), R.color.colorAccent));
            snackbar.setAction("Restore tabs", createUndoSnackBarListener(snackbar, index, tabs));
            snackbar.show();

        }

        @NonNull
        private View.OnClickListener createUndoSnackBarListener(@NonNull final Snackbar snackbar,
                                                                final int index,
                                                                @NonNull Tab... tabs) {
            return v -> {
                snackbar.setAction(null, null);
                if (tabSwitcher.isSwitcherShown()) {
                    tabSwitcher.addAllTabs(tabs, index);
                }
            };
        }
    }
}
```

```java
package com.origgon.origin.widgets;

import android.content.Context;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.design.widget.BottomNavigationView;
import android.support.v7.widget.Toolbar;
import android.view.LayoutInflater;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.TextView;

import com.origgon.origin.R;

import de.mrapp.android.tabswitcher.Animation;
import de.mrapp.android.tabswitcher.PeekAnimation;
import de.mrapp.android.tabswitcher.RevealAnimation;
import de.mrapp.android.tabswitcher.Tab;
import de.mrapp.android.tabswitcher.TabSwitcher;
import de.mrapp.android.tabswitcher.TabSwitcherDecorator;

import static com.origgon.origin.util.Utils.VIEW_TYPE_EXTRA;

/**
 * Created by rkodekar on 5/12/17.
 */

public class Decorator extends TabSwitcherDecorator {

    private TextView title;
    private Toolbar toolbar;
    private TextView message;
    private FrameLayout content;
    private BottomNavigationView navigation;
    private LinearLayout container;
    private TabSwitcher tabSwitcher;

    public Decorator(TabSwitcher tabSwitcher) {
        this.tabSwitcher = tabSwitcher;
    }

    @NonNull
    @Override
    public View onInflateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup parent, int viewType) {
        View view = inflater.inflate(R.layout.mainframe, parent, false);
        this.container = (LinearLayout) view.findViewById(R.id.container);
        this.navigation = (BottomNavigationView) view.findViewById(R.id.navigation);
        this.content = (FrameLayout) view.findViewById(R.id.content);
        this.message = (TextView) view.findViewById(R.id.message);
        this.toolbar = (Toolbar) view.findViewById(R.id.toolbar);
        this.title = (TextView) view.findViewById(android.R.id.title);
        toolbar.inflateMenu(R.menu.tab);
        toolbar.setOnMenuItemClickListener(createToolbarMenulistener());
        Menu menu = toolbar.getMenu();
        TabSwitcher.setupWithMenu(tabSwitcher, menu, createTabSwitcherButtonListener());
        return view;
    }

    @Override
    public void onShowTab(@NonNull Context context, @NonNull TabSwitcher tabSwitcher, @NonNull View view, @NonNull Tab tab, int index, int viewType, @Nullable Bundle savedInstanceState) {
        title.setText(tab.getTitle());
        toolbar.setVisibility(tabSwitcher.isSwitcherShown() ? View.GONE: View.VISIBLE);
        if (savedInstanceState != null) {

        } else {

        }
    }

    @NonNull
    public Toolbar.OnMenuItemClickListener createToolbarMenulistener() {
        return item -> {
            switch (item.getItemId()) {
                case R.id.add_tab_menu_item:
                    int index = tabSwitcher.getCount();
                    Tab tab = createTab(index);

                    if (tabSwitcher.isSwitcherShown()) {
                        tabSwitcher.addTab(tab, 0, createRevealAnimation());
                    } else {
                        tabSwitcher.addTab(tab, 0, createPeekAnimation());
                    }

                    return true;
                case R.id.clear_tabs_menu_item:
                    tabSwitcher.clear();
                    return true;
                default:
                    return false;
            }
        };
    }

    @Override
    public void onSaveInstanceState(@NonNull View view, @NonNull Tab tab, int index, int viewType, @NonNull Bundle outState) {
        super.onSaveInstanceState(view, tab, index, viewType, outState);
    }

    @Override
    public int getViewType(@NonNull Tab tab, int index) {
        Bundle parameter = tab.getParameters();
        return parameter != null ? parameter.getInt(VIEW_TYPE_EXTRA) : 0;
    }

    @Override
    public int getViewTypeCount() {
        return 1;
    }

    public Tab createTab(int index) {
        CharSequence title = tabSwitcher.getContext().getString(R.string.tab_title, index + 1);
        Tab tab = new Tab(title);
        Bundle parameters = new Bundle();
        parameters.putInt(VIEW_TYPE_EXTRA, index % 2);
        tab.setParameters(parameters);
        return tab;
    }

    @Nullable
    private View getNavigationMenuItem() {
        Toolbar[] toolbars = tabSwitcher.getToolbars();

        if (toolbars != null) {
            Toolbar toolbar = toolbars.length > 1 ? toolbars[1] : toolbars[0];
            int size = toolbar.getChildCount();

            for (int i = 0; i < size; i++) {
                View child = toolbar.getChildAt(i);

                if (child instanceof ImageButton) {
                    return child;
                }
            }
        }

        return null;
    }

    @NonNull
    public View.OnClickListener createTabSwitcherButtonListener() {
        return v -> tabSwitcher.toggleSwitcherVisibility();
    }

    @NonNull
    public Animation createRevealAnimation() {
        float x = 0;
        float y = 0;
        View view = getNavigationMenuItem();

        if (view != null) {
            int[] location = new int[2];
            view.getLocationInWindow(location);
            x = location[0] + (view.getWidth() / 2f);
            y = location[1] + (view.getHeight() / 2f);
        }

        return new RevealAnimation.Builder().setX(x).setY(y).create();
    }

    @NonNull
    public Animation createPeekAnimation() {
        return new PeekAnimation.Builder().setX(tabSwitcher.getWidth() / 2f).create();
    }
}
```

**Comment by michael-rapp** [comment]
Could you please send me a working Android Studio project, which allows to reproduce the issue? It requires much effort for me to build a working example. Especially because I don't have any experience using the mortar library. I think, that using this library is likely to cause the issue.

**Comment by mkodekar** [comment]
actually i reverted back to activity base , can i send you the link of a github project that would help you understand the project ?

**Comment by michael-rapp** [comment]
Yes, that would be fine.

**Comment by mkodekar** [comment]
https://github.com/mkodekar/Mortar-Flow-Dagger2-demo here is an example of the same please have a look

**Comment by michael-rapp** [comment]
I took a closer look at the stacktrace you posted and I realized, that the following is happening there: 

After the orientation change, the view tries to restore its previous state. The NullPointerException, which is thrown when doing so, is caused because no `TabSwitcherDecorator` is applied to the `TabSwitcher`. I will add a more expressive exception for feature releases. However, this will not solve your issue.

As I am not familiar with the libraries you are using, I don't know when exactly the `onLoad`-method in the code you've posted, is called during the activity lifecycle. As it is invoking the `setDecorator`-method, it must be called before the tab switcher's `onRestoreInstanceState`-method is called. Unfortunately, I currently don't have the time to build a working example to reproduce your issue. So either you send me a link to your project, or you have to find a workaround yourself.

**Comment by mkodekar** [comment]
Mortar and flow are now deprecated in some places using magellan i

**Comment by mkodekar** [comment]
i will add an example after completing your example with the other library and report any issue to you

**Comment by michael-rapp** [comment]
Okay, I am waiting for your response.

**Comment by michael-rapp** [comment]
Issue will be closed until further information about how to reproduce the problem is available. I don't even think, that it is relevant anymore since the Mortar flow library is deprecated now.
